name: grespa-webapp
dependencies:
  - python=2.7
  - flask=0.10
  - psycopg2
  - sqlalchemy
  - requests
  - pip:
    - flask_debugtoolbar
    - python-dotenv
    - flask-bootstrap
    - flask-sqlalchemy
    - flask-nav
    - flask-debug
    - flask-cache
    - flask-sqlalchemy-session
    - sqlalchemy-datatables
